WITH  
 REC (CHILDINSTANCEKEY, PARENTINSTANCEKEY, LEVEL, PATH)
 AS (
   SELECT CHILDINSTANCEKEY, PARENTINSTANCEKEY, 0, cast('' as VARCHAR(512))
    FROM TBSMBASE.SERVICEINSTANCERELATIONSHIP
    WHERE CHILDINSTANCEKEY = '8037'
   UNION ALL
   SELECT REL.CHILDINSTANCEKEY, REL.PARENTINSTANCEKEY, LEVEL + 1, CONCAT(CONCAT(PATH, REL.CHILDINSTANCEKEY), '; ')
    FROM TBSMBASE.SERVICEINSTANCERELATIONSHIP REL, REC
    WHERE REC.CHILDINSTANCEKEY = REL.PARENTINSTANCEKEY
   )
 SELECT SERVICEINSTANCENAME, DISPLAYNAME, LEVEL, PATH
 FROM REC, TBSMBASE.SERVICEINSTANCE
 WHERE REC.CHILDINSTANCEKEY = SERVICEINSTANCEID
 
